"use client";

/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "llzrpcbwnqvbrcjjwysm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsenJwY2J3bnF2YnJjamp3eXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzk3ODIsImV4cCI6MjA2ODcxNTc4Mn0.vnXVAoqDhFMlHfo3X31D8tCE8d2-3jtGEjxzDE1If_c"