"use client";

import React from "react";
import {
  LayoutGrid,
  Home,
  Undo2,
  Redo2,
  Search,
  Bell,
  HelpCircle,
  Settings,
  StickyNote,
  Link2,
  ListChecks,
  Spline,
  Image as ImageIcon,
  Upload,
  PenTool,
  Trash2,
  MoreHorizontal,
  Plus,
  Minus,
  FileText,
  Target,
  Camera,
  Layers,
  PenLine,
  Code,
  Rocket,
  Megaphone,
  Lightbulb,
  Calendar,
  Palette,
  Globe,
  File as FileIcon,
  Clock,
  Pin,
  MessageSquare,
  Zap,
  Star,
  Folder,
  Check,
  AlarmClock,
  Download,
  UserPlus,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Copy,
  Shapes,
  Eye,
  Type,
  ExternalLink,
  Maximize2,
  Minimize2,
  Play,
  Heading1,
  Heading2,
  Bold,
  Italic,
  List,
  ListOrdered,
  Quote,
  X,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  board: LayoutGrid,
  home: Home,
  undo: Undo2,
  redo: Redo2,
  search: Search,
  bell: Bell,
  help: HelpCircle,
  settings: Settings,
  note: StickyNote,
  link: Link2,
  todo: ListChecks,
  line: Spline,
  image: ImageIcon,
  upload: Upload,
  draw: PenTool,
  trash: Trash2,
  more: MoreHorizontal,
  plus: Plus,
  minus: Minus,
  doc: FileText,
  target: Target,
  camera: Camera,
  layers: Layers,
  pen: PenLine,
  code: Code,
  rocket: Rocket,
  megaphone: Megaphone,
  bulb: Lightbulb,
  calendar: Calendar,
  palette: Palette,
  globe: Globe,
  file: FileIcon,
  clock: Clock,
  pin: Pin,
  comment: MessageSquare,
  zap: Zap,
  star: Star,
  folder: Folder,
  check: Check,
  alarm: AlarmClock,
  download: Download,
  userPlus: UserPlus,
  chevdown: ChevronDown,
  chevron: ChevronRight,
  back: ChevronLeft,
  copy: Copy,
  swatch: Shapes,
  eye: Eye,
  type: Type,
  external: ExternalLink,
  expand: Maximize2,
  collapse: Minimize2,
  play: Play,
  h1: Heading1,
  h2: Heading2,
  bold: Bold,
  italic: Italic,
  listUl: List,
  listOl: ListOrdered,
  quote: Quote,
  x: X,
  column: LayoutGrid,
  table: LayoutGrid,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  // Digits 0-9 are rendered as (non-editable) text, treated like an icon.
  if (/^[0-9]$/.test(name)) {
    return <span className={`${className ?? ""} ico-num`}>{name}</span>;
  }
  const Cmp = MAP[name] ?? LayoutGrid;
  return <Cmp className={className} strokeWidth={1.8} />;
}

export default Icon;
